#!/bin/bash

# Function to sort an array using bubble sort
bubble_sort() {
    local -a arr=(882 325 169 627 347 504 67)
    # Iterate over the array, swapping adjacent elements if they are out of order
    for ((i = 0; i < ${#arr[@]}; i++)); do
        for ((j = 0; j < ${#arr[@]}-1; j++)); do
            if [[ ${arr[j]} -gt ${arr[j+1]} ]]; then
                # Swap elements
                temp=${arr[j]}
                arr[j]=${arr[j+1]}
                arr[j+1]=$temp
            fi
        done
    done
    echo "${arr[*]}"
}

bubble_sort
